### ISSUE TITLE
2.0.0 is not available in Maven Central

### ISSUE THREAD

**Issue by arvindkrishnakumar-okta** [Jasig/maven-notice-plugin#24]
Per https://github.com/Jasig/maven-notice-plugin/releases, the latest appears to be `2.0.0`, but this version is not (yet) found in Maven Central.

https://repo1.maven.org/maven2/org/jasig/maven/maven-notice-plugin/

`[ERROR] Plugin org.jasig.maven:maven-notice-plugin:2.0.0 or one of its dependencies could not be resolved: Could not find artifact org.jasig.maven:maven-notice-plugin:jar:2.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by ChristianMurphy** [comment]
Please read the changelog for 2.0.0

> The convention naming for maven plugins required a name change from maven-notice-plugin to notice-maven-plugin

https://github.com/Jasig/maven-notice-plugin/releases/tag/notice-maven-plugin-2.0.0

The release is available under the new identifier https://repo1.maven.org/maven2/org/jasig/maven/notice-maven-plugin/
